import {
  Braces,
  Binary,
  Link,
  Palette,
  Regex,
  KeyRound,
  Code2,
  GitCompare,
  FileCode,
  Image,
  Paintbrush,
  BoxSelect,
  FileSpreadsheet,
  FileText,
  Calendar,
  SwatchBook,
  Minimize2,
  Clock,
  ArrowLeftRight,
  Lock,
  LetterText,
  QrCode,
  CaseSensitive,
  Fingerprint,
  AlignLeft,
  Hash,
  Percent,
  Timer,
  ArrowDownUp,
  Ruler,
  WrapText,
  Calculator,
  CalendarClock,
  Shuffle,
  Sparkles,
  Radio,
  DollarSign,
  ShieldCheck,
  Database,
  BarChart3,
  Share2,
  Search,
  MousePointerClick,
} from "lucide-react";

export const toolsList = [
  // === Original Tools ===
  { title: "JSON Formatter", description: "Format, validate and minify JSON data", href: "/json", icon: Braces, color: "primary" as const },
  { title: "Base64 Tool", description: "Encode and decode Base64 strings", href: "/base64", icon: Binary, color: "cyan" as const },
  { title: "URL Tool", description: "Encode, decode and parse URLs", href: "/url", icon: Link, color: "amber" as const },
  { title: "Color Tool", description: "Convert between HEX, RGB, HSL formats", href: "/color", icon: Palette, color: "violet" as const },
  { title: "Regex Tool", description: "Test and debug regular expressions", href: "/regex", icon: Regex, color: "primary" as const },
  { title: "JWT Tool", description: "Decode and inspect JWT tokens", href: "/jwt", icon: KeyRound, color: "cyan" as const },
  { title: "Code Formatter", description: "Format and beautify code snippets", href: "/code-formatter", icon: Code2, color: "amber" as const },
  { title: "Code Diff", description: "Compare two code snippets side by side", href: "/code-diff", icon: GitCompare, color: "violet" as const },
  { title: "XML Tool", description: "Format, validate and minify XML data", href: "/xml", icon: FileCode, color: "primary" as const },
  // === Phase 1 — Quick Wins ===
  { title: "Password Generator", description: "Generate secure random passwords", href: "/password-generator", icon: Lock, color: "cyan" as const },
  { title: "Word Counter", description: "Count words, characters, sentences and more", href: "/word-counter", icon: LetterText, color: "amber" as const },
  { title: "QR Code Generator", description: "Generate QR codes from text or URLs", href: "/qr-code", icon: QrCode, color: "violet" as const },
  { title: "Case Converter", description: "Convert text between 12 case formats", href: "/case-converter", icon: CaseSensitive, color: "primary" as const },
  { title: "UUID Generator", description: "Generate and validate UUID v4 identifiers", href: "/uuid-generator", icon: Fingerprint, color: "cyan" as const },
  { title: "Lorem Ipsum", description: "Generate placeholder text for designs", href: "/lorem-ipsum", icon: AlignLeft, color: "amber" as const },
  { title: "Hash Generator", description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes", href: "/hash-generator", icon: Hash, color: "violet" as const },
  { title: "Percentage Calculator", description: "Calculate percentages four different ways", href: "/percentage-calculator", icon: Percent, color: "primary" as const },
  { title: "Unix Timestamp", description: "Convert between Unix timestamps and dates", href: "/timestamp-converter", icon: Timer, color: "cyan" as const },
  { title: "Number Base Converter", description: "Convert between decimal, binary, hex, octal", href: "/number-base", icon: ArrowDownUp, color: "amber" as const },
  // === Phase 2 — High-Value ===
  { title: "Image Base64", description: "Convert images to Base64 and back", href: "/image-base64", icon: Image, color: "violet" as const },
  { title: "CSS Gradient", description: "Generate CSS gradient code visually", href: "/css-gradient", icon: Paintbrush, color: "primary" as const },
  { title: "CSS Box Shadow", description: "Design box shadows with live preview", href: "/css-box-shadow", icon: BoxSelect, color: "cyan" as const },
  { title: "JSON ↔ CSV", description: "Convert between JSON and CSV formats", href: "/json-csv", icon: FileSpreadsheet, color: "amber" as const },
  { title: "Markdown ↔ HTML", description: "Convert Markdown to HTML and back", href: "/markdown", icon: FileText, color: "violet" as const },
  { title: "Age Calculator", description: "Calculate exact age from date of birth", href: "/age-calculator", icon: Calendar, color: "primary" as const },
  { title: "Color Palette", description: "Generate harmonious color palettes", href: "/color-palette", icon: SwatchBook, color: "cyan" as const },
  { title: "Minifier", description: "Minify and beautify HTML, CSS, JavaScript", href: "/minifier", icon: Minimize2, color: "amber" as const },
  { title: "Cron Generator", description: "Build and parse cron expressions", href: "/cron", icon: Clock, color: "violet" as const },
  { title: "Text ↔ Binary", description: "Convert text to binary, hex, decimal, octal", href: "/text-binary", icon: ArrowLeftRight, color: "primary" as const },
  // === Phase 3 — Long Tail ===
  { title: "Unit Converter", description: "Convert length, weight, temperature and more", href: "/unit-converter", icon: Ruler, color: "cyan" as const },
  { title: "Text Tools", description: "Sort, deduplicate, reverse, find & replace text", href: "/text-tools", icon: WrapText, color: "amber" as const },
  { title: "Math Tools", description: "Average, fractions, GCF, primes, BMI and more", href: "/math-tools", icon: Calculator, color: "violet" as const },
  { title: "Date & Time Tools", description: "Date diff, countdown, stopwatch, time zones", href: "/date-time", icon: CalendarClock, color: "primary" as const },
  { title: "Random Generators", description: "Random numbers, names, dice, coins and more", href: "/random-generators", icon: Shuffle, color: "cyan" as const },
  { title: "Fancy Text", description: "Bold, italic, gothic, upside down Unicode text", href: "/fancy-text", icon: Sparkles, color: "amber" as const },
  { title: "Morse Code", description: "Translate text to Morse code with audio playback", href: "/morse-code", icon: Radio, color: "violet" as const },
  { title: "Finance Tools", description: "Compound interest, mortgage, loan calculators", href: "/finance-tools", icon: DollarSign, color: "primary" as const },
  { title: "String Encoder", description: "HTML entities, ROT13, hex, JSON, SQL escape", href: "/string-encoder", icon: ShieldCheck, color: "cyan" as const },
  { title: "Data Converter", description: "Convert between JSON, YAML, XML, CSV, SQL", href: "/data-converter", icon: Database, color: "amber" as const },
  // === Phase 4 — Differentiators ===
  { title: "Image Tools", description: "Compress, resize, convert, crop, rotate images", href: "/image-tools", icon: Image, color: "violet" as const },
  { title: "Chart Maker", description: "Create bar, pie, line and doughnut charts", href: "/chart-maker", icon: BarChart3, color: "primary" as const },
  { title: "CSS Tools", description: "Border radius, flexbox, grid, glassmorphism generators", href: "/css-tools", icon: Paintbrush, color: "cyan" as const },
  { title: "Social Media Tools", description: "YouTube thumbnails, OG tags, emoji picker", href: "/social-media", icon: Share2, color: "amber" as const },
  { title: "SEO Tools", description: "Schema markup, robots.txt, slug, headline analyzer", href: "/seo-tools", icon: Search, color: "violet" as const },
  { title: "Interactive Tools", description: "Click speed test, typing test, contrast checker", href: "/interactive-tools", icon: MousePointerClick, color: "primary" as const },
];
